package marketplace

// emit_setup.go — the ./setup launcher at the marketplace root.
//
// The marketplace is the standalone opencharly/marketplace repo, and it deliberately carries
// NO charly submodule: the refs downloader initializes every declared submodule on fetch, so
// declaring one dragged the whole charly repo into consumer fetch trees. The launcher therefore
// cannot assume a `./charly` checkout — it resolves one from $CHARLY_SRC, defaulting to a
// sibling clone, which is the layout the opencharly umbrella provides and the one charly's
// taskfiles/Skills.yml already assumes from the other side (`{{.ROOT_DIR}}/../marketplace`).
//
// Both paths are passed absolute. `--out ..` used to be the parent of the charly checkout, which
// is only the marketplace when charly is nested inside it — the arrangement that no longer
// exists. `--check` maps to the drift gate.

const setupLauncher = "#!/usr/bin/env bash\n" +
	"# GENERATED by charly marketplace generate — DO NOT EDIT.\n" +
	"# Regenerate this marketplace from a charly checkout:\n" +
	"#   ./setup           generate the corpus into this repo\n" +
	"#   ./setup --check   fail-closed drift gate (regeneration must be a no-op)\n" +
	"#\n" +
	"# This repo carries NO charly submodule on purpose: a declared submodule is initialized on\n" +
	"# every fetch, which dragged the whole charly repo into consumer trees. Keep a charly clone\n" +
	"# beside this repo (the umbrella layout), or point CHARLY_SRC at one.\n" +
	"set -euo pipefail\n" +
	"here=\"$(cd \"$(dirname \"$0\")\" && pwd)\"\n" +
	"charly_src=\"${CHARLY_SRC:-$here/../charly}\"\n" +
	"if [ ! -f \"$charly_src/charly.yml\" ]; then\n" +
	"    echo \"setup: no charly checkout at $charly_src\" >&2\n" +
	"    echo \"  clone opencharly/charly next to this repo, or set CHARLY_SRC=/path/to/charly\" >&2\n" +
	"    exit 1\n" +
	"fi\n" +
	"charly_src=\"$(cd \"$charly_src\" && pwd)\"\n" +
	"# The charly CLI prescans the 'marketplace' word from the project root it runs in,\n" +
	"# so the command executes FROM the charly checkout; --root/--out stay explicit.\n" +
	"cd \"$charly_src\"\n" +
	"for arg in \"$@\"; do\n" +
	"    if [ \"$arg\" = \"--check\" ] || [ \"$arg\" = \"--dry-run\" ]; then\n" +
	"        exec charly marketplace drift --root \"$charly_src\" --out \"$here\"\n" +
	"    fi\n" +
	"done\n" +
	"exec charly marketplace generate --root \"$charly_src\" --out \"$here\"\n"

func emitSetup(em emissions) {
	em["plugins/setup"] = []byte(setupLauncher)
}
