package marketplace

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
)

// emit.go — the generated-artifact contract: a DO-NOT-EDIT header + the emit map (path → bytes,
// relative to the repo root) both `generate` and `drift` build. The header marks markdown files
// for the prune pass (a file carrying it is generated; a file without it is hand-authored and
// preserved — the boundary is content, never location). JSON files cannot carry a markdown
// header, so they are pruned by known path instead (see prune.go).

// generatedHeader marks a markdown artifact as generator output.
const generatedHeader = "<!-- GENERATED by `charly marketplace generate` — DO NOT EDIT. Edit the candy's skill:/hook:/marketplace: entities and regenerate. -->"

// generatedHeaderLine is the header plus a trailing blank line, for placing AFTER a file's
// frontmatter (frontmatter must be byte-zero for the Skill-tool/validate_skills parser).
const generatedHeaderBlock = generatedHeader + "\n\n"

// emissions is the full generated artifact set, keyed by a canonical path: corpus artifacts
// carry the legacy "plugins/" prefix (stripped when written under --out), harness-surface
// artifacts (.claude/, CLAUDE.md, AGENTS.md) carry none (always written under --root).
type emissions map[string][]byte

// corpusPrefix marks the corpus half of the emission set. The prefix is historical — the corpus
// used to live at <root>/plugins; it now lives at the marketplace repo root, so writeAll strips it.
const corpusPrefix = "plugins/"

// writeAll writes every emitted artifact, creating parent directories. Corpus artifacts (the
// plugins/ tree) are written under out (the marketplace corpus root) with the prefix stripped;
// the harness-surface artifacts (.claude/, CLAUDE.md, AGENTS.md) go under root (the charly
// checkout). The corpus destination is always explicit (--out is required since the
// de-submodule cutover — the marketplace is a standalone repo).
func (em emissions) writeAll(root, out string) error {
	for rel, b := range em {
		base, target := root, rel
		if strings.HasPrefix(rel, corpusPrefix) {
			base, target = out, strings.TrimPrefix(rel, corpusPrefix)
		}
		path := filepath.Join(base, filepath.FromSlash(target))
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(path, b, 0o644); err != nil {
			return err
		}
	}
	return nil
}

// hasGeneratedHeader reports whether a file carries the generated header.
func hasGeneratedHeader(b []byte) bool { return bytes.Contains(b, []byte(generatedHeader)) }

// readOnDisk reads a repo-root-relative path's bytes, or nil when absent.
func readOnDisk(root, rel string) ([]byte, error) {
	b, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(rel)))
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, err
	}
	return b, nil
}

// fileKey normalizes a path for map keys.
func fileKey(root, abs string) string {
	rel, err := filepath.Rel(root, abs)
	if err != nil {
		return abs
	}
	return filepath.ToSlash(rel)
}
